server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: fz-reservation
  datasource:
    url: jdbc:mariadb://localhost:3306/fz_reservation
    username: root
    password: 123456789
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:sql/**/*.xml
  configuration:
    map-underscore-to-camel-case: true